import Head from 'next/head'
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillGitlab,
  AiFillLinkedin,
} from "react-icons/ai"
import { useState } from "react"
import Image from "next/image"

// import myphoto from './assets/me.jpg'
// import myImage from './me.jpg'

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark" : ""} >
      <Head>
        <title>Thato Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/dist/output.css" rel="stylesheet"></link>
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section>
        <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Portfolio by Thato</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Thato Lebethe
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Software Engineer and Mobile Dev.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Soon to be _WethinkCode graduate looking for a home to utalize 
              my new found skills.
            </p>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Get in Touch
            </h3>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              
              <a href='https://gitlab.com/Tlebethe'><AiFillGitlab /></a>
              <a href='https://www.linkedin.com/in/thato-lebethe'><AiFillLinkedin /></a>
              
            </div>

              {/* <Image src={deved} layout="fill" objectFit="cover" /> */}
              <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
                <Image src='/thato.png' layout="fill" objectFit="cover" />
              </div>
            
          </div>
        </section>
        <section>
        <div>
            <h3 className="text-3xl py-1 dark:text-white ">About ME</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Kind , Curious , HardWorking and eager to learn.
            </p>
            <h4 className='text-2xl py-2 dark:text-white '>Why SovTech Graduate Program?</h4>


            <p className="text-md py-1 leading-8 text-gray-800 dark:text-gray-200">
              I belive the SovTech Graduate Program would be the perfect 
              organization to begin my proffesional career.
            </p>
            <p className="text-md py-1 leading-8 text-gray-800 dark:text-gray-200">
              What I love most about SovTech as whole is the tech stack,
              my journey into Software development began out of curiousity, playing
              around with some html and css, and javascript.
              A few years later I am able to build apps using cross platform
              frameworks like react native and flutter,
              as well as build web pages using  html, css, js and react.
            </p>
            <p className="text-md py-1 leading-8 text-gray-800 dark:text-gray-200">
              This is why I belive SovTech would be the perfect organization to develop
              my skills further, not only technically but professionally as well.
            </p>
          </div>
          <h2 className="text-3xl py-1 dark:text-white ">My Skills</h2>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
                <Image src='/java.png' width={100} height={100} className='mx-auto'/>
                <h3 className="text-lg font-medium pt-8 pb-2  ">
                  Java
                </h3>
                <p className="py-2">
                Java is a high-level, class-based, object-oriented programming
                 language that is designed to
                 have as few implementation dependencies as possible.
                </p>
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
                <Image src='/js.png' width={100} height={100} className='mx-auto'/>
                <h3 className="text-lg font-medium pt-8 pb-2  ">
                  Javascript
                </h3>
                <p className="py-2">
                JavaScript, often abbreviated as JS, is a programming 
                language that is one of the core technologies of the World Wide Web,
                 alongside HTML and CSS
                </p>
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
                <Image src='/python.png' width={100} height={100} className='mx-auto'/>
                <h3 className="text-lg font-medium pt-8 pb-2  ">
                  Python
                </h3>
                <p className="py-2">
                Python is a high-level, general-purpose programming language. 
                Its design philosophy emphasizes code
                 readability with the use of significant indentation.
                </p>
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
                <Image src='/react.png' width={100} height={100} className='mx-auto'/>
                <h3 className="text-lg font-medium pt-8 pb-2  ">
                  React Native
                </h3>
                <p className="py-2">
                React Native is an open-source UI software framework
                 created by Meta Platforms, Inc. It is used to develop
                  applications for Android, iOS, 
                   Windows and UWP by enabling developers to use the React
                 framework along with native platform capabilities.
                </p>
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10 mx-auto  dark:bg-white flex-1">
                <Image src='/flutter.png' width={100} height={100} className='mx-auto'/>
                <h3 className="text-lg font-medium pt-8 pb-2  ">
                  Flutter
                </h3>
                <p className="py-2">
                Flutter is an open-source UI software development
                 kit created by Google. It is used to develop cross-platform applications for Android, iOS, Linux, macOS, Windows, Google Fuchsia,
                 and the web from a single codebase.
                </p>
              </div>
          </div>
        </section>

      </main>

    </div>
  )
}
